### ISSUE TITLE
Inconsistent results from the Hawkes demo

### ISSUE THREAD

**Issue by chennanaresearch** [Networks-Learning/LVIV-2018#1]
Hi there,
I cloned the whole folder about Hawkes point process and ran it in Anaconda. However, I got a quite different result from the results shown in your ipynb file. 

When I ran the file "Hawkes-demo.ipynb", I got "alpha_opt = 0.9979165614874713, alpha_true = 0.5" and "lambda_opt = 0.2278797493605351, lambda_true = 1". 

Why the estimation result is so far away from the true value?

Thanks,
Ruby

**Comment by musically-ut** [comment]
Which branch of the code were you running?

It would be best to use the branch [`redqueen-solution-2`](https://github.com/Networks-Learning/LVIV-2018/tree/redqueen-solution-2) and use the solution scripts from there-in.

**Comment by chennanaresearch** [comment]
I am mentioning about the "Hawkes-demo.ipynb" in the "hawkes" folder.
It seems that this file was deleted in the branch  redqueen-solution-2 [https://github.com/Networks-Learning/LVIV-2018/tree/redqueen-solution-2](url). Is there something wrong with the prior demo file?
Thanks.

**Comment by musically-ut** [comment]
I just merged `master` into the branch and the Notebook should show up in that branch as well.

Hope that helps.

**Comment by musically-ut** [comment]
I'm assuming that resolved the problem.
If you are still facing any issues, please reopen this issue or create a new issue.
